<div class="card text-white text-center">
  <img src="http://localhost/eCom/Views/Image/font.jpg" class="img-fluid fonce" alt="...">
  <div class="card-img-overlay">
    <h5 class="card-title espace">Les meilleurs plats</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text w-75">Lorem ipsum dolor sit amet, 
		consectetur adipisicing elit. Sunt ex, tempora, 
		hic atque inventore rem quaerat fugiat optio, 
		architecto perferendis nisi repellat voluptates 
		voluptate soluta dicta tempore. Perferendis, architecto eligendi!</p>
		<br>
	<p class="card-text"> <a class="btn-transparent" href="http://localhost/eCom/reservation">RESERVER</a></p>
  </div>
</div>

<!--Cascade-->
<div class="container">
    <div class="row">
        <!-----Cascade---->
    <!---------------------------->
    <div class="distance"></div>
        <div class="col-2 titre2">
        Lorem ipsum dolor sit amet, 
        consectetur adipisicing elit. Totam 
        corrupti veritatis aliquam mollitia 
        qui quod commodi reiciendis quaerat
        </div>
         <div class="col-4">
            <img src="http://localhost/eCom/Views/Image/img2.jpg" alt="" class="img-fluid img1">
         </div>
         <div class="col-6 d-flex align-items-center">
            <div>
                <span class="titre ">
                Lorem ipsum dolor
                </span>
                <div>
                    <span class="griser">
                        Lorem ipsum dolor sit, amet
                        consectetur adipisicing elit.
                        Harum, porro beatae. Consequuntur
                        animi a perferendis corporis rem
                        fuga veniam, iste, aut optio quia 
                        officiis aperiam blanditiis sapiente eius 
                        odio hic?
                    </span>
                </div>
            </div>
            
         </div>
        
        <!---------------------------->
        <div class="distance"></div>
        <div class="col-6 d-flex align-items-center">
            <div>
                <span class="titre ">
                Lorem ipsum dolor
                </span>
                <div>
                    <span class="griser">
                    Lorem ipsum dolor sit, amet
                    consectetur adipisicing elit.
                    Harum, porro beatae. Consequuntur
                    animi a perferendis corporis rem
                    fuga veniam, iste, aut optio quia 
                    officiis aperiam blanditiis sapiente eius 
                    odio hic?
                    </span>
                </div>
            </div>
         </div>
         <div class="col-2 titre2 d-flex align-items-end">Lorem ipsum dolor sit amet, 
        consectetur adipisicing elit. Totam 
        corrupti veritatis aliquam mollitia 
        qui quod commodi reiciendis quaerat
        </div>
         <div class="col-4">
            <img src="http://localhost/eCom/Views/Image/img1.jpg" alt="" class="img-fluid img1">
         </div>
         <div class="distance"></div>
        <!---------------------------->
        
    </div>
</div>

<div class="bg-white">

    <div class="menu-mere">
        <div class="menu">
            <p class="menu-titre">Notre menu</p>
            <p class="menu-griser">Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam, unde? Nisi aut sit reiciendis, nobis adipisi!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda ex aperiam exercitationem ipsum. Iusto molestias quidem, optio, vero nisi consequuntur                        error voluptate illo praesentium sunt asperiores rem aliquam autem nesciunt!
            </p>
        </div>
    </div>

    <!--liste-->
    <div class="liste">
        <div class="row">
                <!-----Listes---->
            <!-----Ligne 1---->
            <div class="col-6">
                <div class="card mb-3" style="max-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="http://localhost/eCom/Views/Image/img3.jpg" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-9">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                    <div class="prix col-3">
                                        45$
                                    </div>
                                </div>
                                
                                <p class="mt-3 pt-3">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <p class="card-text mt-3 pt-3"><small class="text-muted">Last updated 3 mins ago</small></p>                      
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card mb-3" style="max-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="http://localhost/eCom/Views/Image/img4.jpg" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                            <div class="row">
                                    <div class="col-9">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                    <div class="prix col-3">
                                        74$
                                    </div>
                                </div>
                                <p class="mt-3 pt-3 debut">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <p class="card-text mt-3 pt-3"><small class="text-muted">Last updated 3 mins ago</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card mb-3" style="max-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="http://localhost/eCom/Views/Image/img5.jpg" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-9">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                    <div class="prix col-3">
                                        45$
                                    </div>
                                </div>
                                
                                <p class="mt-3 pt-3">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <p class="card-text mt-3 pt-3"><small class="text-muted">Last updated 3 mins ago</small></p>                      
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card mb-3" style="max-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="http://localhost/eCom/Views/Image/img6.jpg" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                            <div class="row">
                                    <div class="col-9">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                    <div class="prix col-3">
                                        74$
                                    </div>
                                </div>
                                <p class="mt-3 pt-3 debut">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <p class="card-text mt-3 pt-3"><small class="text-muted">Last updated 3 mins ago</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card mb-3" style="max-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="http://localhost/eCom/Views/Image/img7.jpg" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-9">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                    <div class="prix col-3">
                                        45$
                                    </div>
                                </div>
                                
                                <p class="mt-3 pt-3">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <p class="card-text mt-3 pt-3"><small class="text-muted">Last updated 3 mins ago</small></p>                      
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card mb-3" style="max-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="http://localhost/eCom/Views/Image/img8.jpg" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                            <div class="row">
                                    <div class="col-9">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                    <div class="prix col-3">
                                        74$
                                    </div>
                                </div>
                                <p class="mt-3 pt-3 debut">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <p class="card-text mt-3 pt-3"><small class="text-muted">Last updated 3 mins ago</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="distance"></div>
        </div>
        
    </div>

</div>

<!--Reservation-->
<div class="menu">
    <p class="call-us-text">Faire une reservation en ligne</p>
    <form action="http://localhost/eCom/paiement" class="form-main-size" method="POST">
            <input name="nom" type="text" placeholder="Nom complet" class="form-size">
            <input name="nbrePersonne" type="number" placeholder="Nombre de personnes (Max 5)" class="form-size" value="2">
            <br>
            <input name="tel" type="tel" placeholder="Numero de telephone" class="form-size">
            <input name="date" type="date" placeholder="Date" class="form-size" value="<?= date("Y-m-d")?>">
            <br>
            <input name="email" type="email" placeholder="Adresse email" class="form-size">
            <input name="heure" type="time" placeholder="Heure" class="form-size" value="21:00">
            <br>
            <div class="distance"></div>
            <input type="submit" value="Reserver" class="contact-btn">
        </form>
    <div class="distance"></div>

</div>

