<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="author" content="Karamoko Coulibaly">
		<meta charset="UTF-8" />
		<!----------------->
		<title><?= $title ?></title>
		<meta name="description" content="<?= $description ?>" />
		<!----------------->
		<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
		 rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" 
		 crossorigin="anonymous">-->
		 <!--<link href="./assets/dist/css/bootstrap.min.css" rel="stylesheet">-->
		<!--<link href="http://localhost/eCom/eCom/Views/assets/dist/css/bootstrap.min.css" rel="stylesheet">-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<link href="http://localhost/eCom/style.css" rel="stylesheet" type="text/css"/>
	</head>

<body class="body">
<ul id="haut" class="nav justify-content-center">

      <li class="nav-item">
        <a class="nav-link" href="http://localhost/eCom/home">Acceuil</a>
      </li>
	  <li class="nav-item">
        <a class="nav-link" href="http://localhost/eCom/reservation">Reservation</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">FAQs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost/eCom/contact">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">A propos</a>
      </li>
    </ul>

</div>
<div class="main">
	<?php $this->controller->renderView(); // renders the current view into the template ?>
</div>
	<footer class="foot text-center">
	<div class="footer-head">Footer</div>
	<div class="footer-bottom">
	<p>Sample tutorial of a simple MVC from <a href="http://www.ict.social" target="_blank">ict.social</a> - The social network for programmers.</p>
	</div>
	</footer>
</body>
</html>
